config/routes.rb
Rails.application.routes.draw do
  resources :clases
  resources :lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clase.rb
class Clase < ApplicationRecord
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clases_controller.rb
class ClasesController < ApplicationController
  before_action :set_clase, only: [:show, :edit, :update, :destroy]

  # GET /clases
  # GET /clases.json
  def index
    @clases = Clase.all
  end

  # GET /clases/1
  # GET /clases/1.json
  def show
  end

  # GET /clases/new
  def new
    @clase = Clase.new
  end

  # GET /clases/1/edit
  def edit
  end

  # POST /clases
  # POST /clases.json
  def create
    @clase = Clase.new(clase_params)

    respond_to do |format|
      if @clase.save
        format.html { redirect_to @clase, notice: 'Clase was successfully created.' }
        format.json { render :show, status: :created, location: @clase }
      else
        format.html { render :new }
        format.json { render json: @clase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clases/1
  # PATCH/PUT /clases/1.json
  def update
    respond_to do |format|
      if @clase.update(clase_params)
        format.html { redirect_to @clase, notice: 'Clase was successfully updated.' }
        format.json { render :show, status: :ok, location: @clase }
      else
        format.html { render :edit }
        format.json { render json: @clase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clases/1
  # DELETE /clases/1.json
  def destroy
    @clase.destroy
    respond_to do |format|
      format.html { redirect_to clases_url, notice: 'Clase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clase
      @clase = Clase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clase_params
      params.require(:clase).permit(:clase, :seccion)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :lastname, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/clases/_form.html.erb
<%= form_with(model: clase, local: true) do |form| %>
  <% if clase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clase.errors.count, "error") %> prohibited this clase from being saved:</h2>

      <ul>
      <% clase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :clase %>
    <%= form.text_area :clase, id: :clase_clase %>
  </div>

  <div class="field">
    <%= form.label :seccion %>
    <%= form.text_area :seccion, id: :clase_seccion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clases/edit.html.erb
<h1>Editing Clase</h1>

<%= render 'form', clase: @clase %>

<%= link_to 'Show', @clase %> |
<%= link_to 'Back', clases_path %>

app/views/clases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clases</h1>

<table>
  <thead>
    <tr>
      <th>Clase</th>
      <th>Seccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clases.each do |clase| %>
      <tr>
        <td><%= clase.clase %></td>
        <td><%= clase.seccion %></td>
        <td><%= link_to 'Show', clase %></td>
        <td><%= link_to 'Edit', edit_clase_path(clase) %></td>
        <td><%= link_to 'Destroy', clase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clase', new_clase_path %>

app/views/clases/new.html.erb
<h1>New Clase</h1>

<%= render 'form', clase: @clase %>

<%= link_to 'Back', clases_path %>

app/views/clases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clase:</strong>
  <%= @clase.clase %>
</p>

<p>
  <strong>Seccion:</strong>
  <%= @clase.seccion %>
</p>

<%= link_to 'Edit', edit_clase_path(@clase) %> |
<%= link_to 'Back', clases_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Register</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      
      <link rel="stylesheet" type="text/css" href="CSS.css">
<style type="text/css">  
body 
{  
background-image: url(https://news.marvel.com/wp-content/uploads/sites/28/2016/10/57ed72cbc3d2c.jpg);
background-size: 100%;
background-repeat: no-repeat
}
</style> 
  
</body> 
      
      
      
      
      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :name, id: :list_name %>
  </div>

  <div class="field">
    <%= form.label :Last_Name %>
    <%= form.text_field :lastname, id: :list_lastname %>
  </div>

  <div class="field">
    <%= form.label :Phone %>
    <%= form.text_area :phone, id: :list_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  
  <link rel="stylesheet" type="text/css" href="CSS.css">
<style type="text/css">  
body 
{  
background-image: url(https://news.marvel.com/wp-content/uploads/sites/28/2016/10/57ed72cbc3d2c.jpg);
background-size: 100%;
background-repeat: no-repeat
}
</style> 
  
</body> 
  
  
  
  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.lastname %></td>
        <td><%= list.phone %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @list.lastname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @list.phone %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>